### ISSUE TITLE
delete the old dot chat organization

### ISSUE THREAD

**Issue by AlurDesign** [Seltorn/Seltorn#2]

**Comment by AlurDesign** [comment]
also delete your tweets about dot chat since i don't want you to be associated with it at all

**Comment by SapphireDisD** [comment]
No

**Comment by SapphireDisD** [comment]
I have to migrate people from Dot Chat to this.

**Comment by AlurDesign** [comment]
No you don't. Literally no one knows about dot chat and it's my name so i want to get the organization.

**Comment by AlurDesign** [comment]
Also you're spreading fake news which is not okay

**Comment by SapphireDisD** [comment]
Fake news? Look at what you said in Discord DMs.

**Comment by SapphireDisD** [comment]
Oh right, you left the group :^)
