### ISSUE TITLE
New issue 

### ISSUE THREAD

**Issue by AlurDesign** [Seltorn/Seltorn#3]
Creating a new issue since you closed the old one;

Keeping the old Dot Chat organization won't make people move to seltron. It's using my name and icon so I want to own the organization.

BTW delete your tweets because you're spreading fake info about stuff that I never did.

**Comment by SapphireDisD** [comment]
Stop

**Comment by AlurDesign** [comment]
I won't stop until you get rid of the organization and tweets.

**Comment by SapphireDisD** [comment]
The user was blocked and this issue will be deleted.
